name: Run CFNB Regularly

on:
  workflow_dispatch: # 支持你随时手动点击运行
  schedule:
    - cron: '0 */2 * * *' # 每 2 小时全自动开机运行一次，完全不消耗你自己的电脑

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run main script
      run: |
        python main.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ip.txt
        git commit -m "Automated IP Update" || exit 0
        git push
